In [151]:
import numpy as np
imA = np.zeros((4,4))
imB = np.zeros((4,4))

imA[:,:]=2
print('imA:\n',imA,'\n')

imB[:,:]=3
print('imB:\n',imB,'\n')

avgA = (300,300)
avgB = (295,305)
shift_x = avgA[0]-avgB[0]
shift_y = avgA[1]-avgB[1]

print(shift_x,shift_y)

result = np.zeros((imA.shape[1]+abs(avgA[1]-avgB[1]),imA.shape[0]+abs(avgA[0]-avgB[0])))
result[:,:]=-np.inf

print('result:\n',result)
right,shift_x = (abs(shift_x),0) if shift_x<0 else (0,shift_x) 
down,shift_y = (abs(shift_y),0) if shift_y<0 else (0,shift_y) 
result[shift_y:(imA.shape[1]+shift_y),shift_x:(imA.shape[0]+shift_x)]= \
np.where(result[shift_y:(imA.shape[1]+shift_y),shift_x:(imA.shape[0]+shift_x)]==-np.inf, \
imA,result[shift_y:(imA.shape[1]+shift_y),shift_x:(imA.shape[0]+shift_x)])
result[down:(imB.shape[1]+down),right:(imB.shape[0]+right)]= \
np.where(result[down:(imB.shape[1]+down),right:(imB.shape[0]+right)]==-np.inf, \
imB,result[down:(imB.shape[1]+down),right:(imB.shape[0]+right)])
print('result:\n',result)
 

imA:
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]] 

imB:
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]] 

5 -5
result:
 [[-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]]
result:
 [[-inf -inf -inf -inf -inf   2.   2.   2.   2.]
 [-inf -inf -inf -inf -inf   2.   2.   2.   2.]
 [-inf -inf -inf -inf -inf   2.   2.   2.   2.]
 [-inf -inf -inf -inf -inf   2.   2.   2.   2.]
 [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
 [  3.   3.   3.   3. -inf -inf -inf -inf -inf]
 [  3.   3.   3.   3. -inf -inf -inf -inf -inf]
 [  3.   3.   3.   3. -inf -inf -inf -inf -inf]
 [  3.   3.   3.   3. 